kumuluzee:
  name: comments
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082

  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                              <Configuration name="image-catalog">
                                  <Appenders>
                                      <Console name="console" target="SYSTEM_OUT">
                                          <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                      </Console>
                                      <Socket name="logstash" host="503d2b4c-2428-422f-814d-9143fe7cfbea-ls.logit.io"
                                      port="11990" protocol="tcp">
                                          <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                      </Socket>
                                  </Appenders>
                                  <Loggers>
                                      <!-- Default logger -->
                                      <Root level="all">
                                          <AppenderRef ref="console" level="info"/>
                                          <AppenderRef ref="logstash" level="trace"/>
                                      </Root>
                                  </Loggers>
                              </Configuration>'

  metrics:
    servlet:
      enabled: true
      mapping: /comments-metrics
    web-instrumentation:
      - name: comments-endpoint
        url-pattern: /v1/comments/*



configuration-properties:
  comments:
    enabled: true
